name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --file ./Dockerfile . \